##### BEGIN image/Dockerfile/image-header #####
FROM vcwebio/conteco.controlplane.base AS base
##### END image/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN image/Dockerfile/env-labels-footer #####
ENV CONTECO_NAME="soleco" \
    CONTECO_TAG="v2.0.4" \
    CONTECO_BASE="controlplane.base" \
    CONTECO_BUILD="image"
LABEL io.vcweb.name="soleco" \
      io.vcweb.tag="v2.0.4" \
      io.vcweb.base="controlplane.base" \
      io.vcweb.build="image" \
      io.vcweb.label=" controlplane.soleco - Conteco" \
      io.vcweb.description="The Conteco controlplane soleco for containerised solutions." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.controlplane.soleco --help" 
##### END image/Dockerfile/env-labels-footer #####
