#!/usr/bin/env bash

export CONTECO_LABEL=" controlplane.soleco - Conteco"
export CONTECO_DESCRIPTION="The Conteco controlplane soleco for containerised solutions."

export CONTECO_TYPE="controlplane"
export CONTECO_NAME="soleco"
export CONTECO_TAG="v2.1.1"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="controlplane.base"
export CONTECO_BUILD="image"
